server.port=8080
spring.application.name=demo_rag_app

# Logging
logging.level.root=INFO
logging.level.com.rag=DEBUG

# OpenAI
openai.api.key=YOUR_OPENAI_API_KEY
openai.api.url=https://api.openai.com/v1
openai.model.embedding=text-embedding-3-small
openai.model.chat=gpt-4o-mini

# Qdrant
qdrant.url=http://localhost:6333
qdrant.collection=documents
qdrant.topK=3

# RAG
rag.chunk-size=500
rag.chunk-overlap=50
rag.max-context-size=2000

# WebClient timeout
webclient.timeout.connect=5000
webclient.timeout.read=10000
